// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-5A3HKd72GJvm_7Z20rKpvoq6a07Bfmc',
    appId: '1:753339274794:web:36d44179e285c82aba1553',
    messagingSenderId: '753339274794',
    projectId: 'data-fyp',
    authDomain: 'data-fyp.firebaseapp.com',
    storageBucket: 'data-fyp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUes1o5RjtJ0XxVW-ip6Jbtg-rpHUDVcc',
    appId: '1:753339274794:android:406cd1325b34d791ba1553',
    messagingSenderId: '753339274794',
    projectId: 'data-fyp',
    storageBucket: 'data-fyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdhi2srIfEarN1Yxsbv2ABzlp0WKD-Q-I',
    appId: '1:753339274794:ios:00bac92c20fd8214ba1553',
    messagingSenderId: '753339274794',
    projectId: 'data-fyp',
    storageBucket: 'data-fyp.firebasestorage.app',
    iosBundleId: 'com.example.eyeDiseaseDetectionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdhi2srIfEarN1Yxsbv2ABzlp0WKD-Q-I',
    appId: '1:753339274794:ios:00bac92c20fd8214ba1553',
    messagingSenderId: '753339274794',
    projectId: 'data-fyp',
    storageBucket: 'data-fyp.firebasestorage.app',
    iosBundleId: 'com.example.eyeDiseaseDetectionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-5A3HKd72GJvm_7Z20rKpvoq6a07Bfmc',
    appId: '1:753339274794:web:76753f7ec54b68eaba1553',
    messagingSenderId: '753339274794',
    projectId: 'data-fyp',
    authDomain: 'data-fyp.firebaseapp.com',
    storageBucket: 'data-fyp.firebasestorage.app',
  );
}
