<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Patient AI Analysis Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 2px solid #604BB0;
        }
        .header h1 {
            color: #604BB0;
            margin: 0;
            padding: 0;
        }
        .section {
            margin-bottom: 20px;
        }
        .section-title {
            color: #604BB0;
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 10px;
        }
        .info-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
            margin-bottom: 20px;
        }
        .info-item {
            margin-bottom: 10px;
        }
        .info-label {
            font-weight: bold;
            color: #666;
        }
        .analysis-results {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        .condition-item {
            margin-bottom: 10px;
            padding: 10px;
            background: #fff;
            border-radius: 5px;
            border-left: 4px solid #604BB0;
        }
        .recommendations {
            list-style-type: none;
            padding: 0;
        }
        .recommendations li {
            margin-bottom: 5px;
            padding-left: 20px;
            position: relative;
        }
        .recommendations li:before {
            content: "•";
            color: #604BB0;
            position: absolute;
            left: 0;
        }
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Patient AI Analysis Report</h1>
        <p>Generated on: {{ now()->format('F d, Y H:i:s') }}</p>
    </div>

    <div class="section">
        <div class="section-title">Patient Information</div>
        <div class="info-grid">
            <div class="info-item">
                <span class="info-label">Name:</span>
                {{ $appointment->user->name }}
            </div>
            <div class="info-item">
                <span class="info-label">Email:</span>
                {{ $appointment->user->email }}
            </div>
            <div class="info-item">
                <span class="info-label">Appointment Date:</span>
                {{ \Carbon\Carbon::parse($appointment->appointment_date)->format('F d, Y') }}
            </div>
            <div class="info-item">
                <span class="info-label">Appointment Time:</span>
                {{ \Carbon\Carbon::parse($appointment->appointment_time)->format('h:i A') }}
            </div>
        </div>
    </div>

    <div class="section">
        <div class="section-title">AI Analysis Results</div>
        <div class="analysis-results">
            <div class="info-item">
                <span class="info-label">Predicted Condition:</span>
                {{ $reportData['predicted_class'] }}
            </div>
            <div class="info-item">
                <span class="info-label">Confidence Level:</span>
                {{ number_format($reportData['confidence'] * 100, 2) }}%
            </div>
        </div>

        <div class="section-title">Detailed Analysis</div>
        @foreach($reportData['conditions'] as $condition)
        <div class="condition-item">
            <div class="info-label">{{ $condition['name'] }}</div>
            <div>Confidence: {{ number_format($condition['confidence'] * 100, 2) }}%</div>
        </div>
        @endforeach
    </div>

    <div class="section">
        <div class="section-title">Recommendations</div>
        <ul class="recommendations">
            @foreach($reportData['recommendations'] as $recommendation)
            <li>{{ $recommendation }}</li>
            @endforeach
        </ul>
    </div>

    <div class="footer">
        <p>This report was generated by the Fundus Disease Analysis System</p>
        <p>For medical advice, please consult with your healthcare provider</p>
    </div>
</body>
</html> 